import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="page">Hello World</div>

        <div className="page">
          <p>OTC market...</p>
          <p>Over the Counter Market의 약자.</p>
          <p>
            우리나라 말로는 장외 시장이라고 하며 암호화폐 거래소 밖에서 거래되는
            시장이다.
          </p>
          <p>
            트레블룰의 적용등으로 보유 흔적을 은익할 수 있는 장외거래가 성장하고
            있다.
          </p>
          <p>최대 장점은 리스크가 없다는 것이다.</p>
        </div>

        <div className="page">
          <p>시장조사</p>
          <p>현재 20여군데가 성업중이다.</p>
          <p>자체조사 구글검색결과 및 마켓스팟광고를 기준으로 조사한다.</p>
          <p>월간 10억에서 60억까지 매출을 올리는 업체들이 있다.</p>
          <p>대부분 사업자 등록 없이 영업중인 것으로 판단된다.</p>
        </div>
        <div className="page">
          <p>전략</p>
          <p>사업방법</p>
          <p>자본금으로 테더를 확보한다.</p>
          <p>주문과 입금을 받고, 테더를 사용해서 주문 코인을 사서보내준다.</p>
          <p>현재 가격대비 수수료 3%가 영업이익이다.</p>
        </div>
        <div className="page">
          <p>문제점</p>
          <p>
            불법자금, 보이스피싱, 마약 관련 자금과 연류시 문제발생 소지 있음.
          </p>
        </div>
        <div className="page">
          <p>예상수익</p>
          <p>일 매출 1,000만원</p>
          <p>일 수익 19만원</p>
          <p>을 기준으로 계산한다.</p>
          <p>테더 구매시 수수료 1.1%를 제외한 금액</p>
        </div>
      </main>

      <footer>
        <div>
          Powered by <span className={styles.logo}></span>
        </div>
      </footer>
      <style jsx>{`
        .page {
          width: 900px;
          height: 100vh;
          margin: 10px auto;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
      `}</style>
    </div>
  );
}
