import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>OTC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="page">Hello World</div>

        <div className="page">
          <p className="title">OTC Market</p>
          <p className="subtitle">Over the Counter Market의 약자.</p>
          <div className="contextBox">
            <p>장외 시장이라고 하며 암호화폐 거래소 밖에서 거래되는 시장.</p>
            <p>
              주요 수요층 : 거래소간 거래신분 추적 시스템인 트래블룰 적용
              시점에서, 코인 보유 흔적을 은익할 수 있는 장외거래가 성장하고
              있다.
              <p style={{ color: "red" }}>
                좀더 구체적인 타켓 설명 추가 필요, 약 3개층 정도로..
              </p>
            </p>
            <p>
              최대 장점 : 리스크가 없다는 것이다. (테더를 그대로 보유 하고 있기
              때문에)
              <p style={{ color: "red" }}>해외 정식 업체 소개 필요</p>
            </p>
          </div>
        </div>

        <div className="page">
          <p className="title">시장 조사</p>
          <div className="contextBox">
            <p>
              {`현재 20여(?) 업체가 성업중이다.`}
              <span style={{ color: "red" }}>현황을 간단히 설명해야...</span>
              <p>자체조사 구글검색결과 및 마켓스팟광고를 기준으로 조사한다.</p>
              <p>대부분 사업자 등록 없이 영업중인 것으로 판단된다.</p>
            </p>

            <p>
              월간 10억에서 60억까지 매출을 올리는 업체들이 있다.
              <p>국내 연간 시장규모는 2,000억원 정도로 추산</p>
            </p>
          </div>
        </div>

        <div className="page">
          <p className="title">전 략</p>
          <div className="contextBox">
            <p>사업방법</p>
            <p>자본금으로 테더를 확보한다.</p>
            <p>주문과 입금을 받고, 테더를 사용해서 주문 코인을 사서보내준다.</p>
            <p>현재 가격대비 수수료 3%가 영업이익이다.</p>
          </div>
        </div>

        <div className="page">
          <p className="title">문제점</p>
          <div className="contextBox">
            <p>
              불법자금, 보이스피싱, 마약 관련 자금과 연류시 문제발생 소지 있음.
            </p>
          </div>
        </div>

        <div className="page">
          <p className="title">예상수익</p>
          <div className="contextBox">
            <p>일 매출 1,000만원</p>
            <p>일 수익 19만원</p>
            <p>을 기준으로 계산한다.</p>
            <p>테더 구매시 수수료 1.1%를 제외한 금액</p>
          </div>
        </div>
      </main>

      <footer>
        <div className="contextBox">
          <span> Powered by azerc</span>
        </div>
      </footer>
      <style jsx>{`
        .page {
          width: 900px;
          height: 100%;
          min-height: 700px;
          margin: 10px auto;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
        .title {
          margin: 0;
          line-height: 1.15;
          font-size: 4rem;
        }
        .subtitle {
          margin: 0;
          line-height: 1.5;
          font-size: 1rem;
          color: gray;
        }
        .contextBox {
          width: 100%;
          padding: 20px;
          margin-top: 50px;
          display: flex;
          flex-direction: column;
          align-items: flex-start;
          justify-content: center;
        }
      `}</style>
    </div>
  );
}
